### ISSUE TITLE
[3] index.html: Header

### ISSUE THREAD

**Issue by Arash-SJPI22** [saeraa/mellankalix#10]
## Details
Links to (placeholder path): Öppettider & Kontakt | Om Spegeln | Biljettinfo | Vill du ha vårt nyhetsbrev? | Köp presentkort
Logo (link to index.html on click)
Social Media icons (placeholder path links)

Styling SCSS - header.scss
Some hover effect
Design up to the developer, artistic freedom!

Two designs: mobile menu, desktop

## Dependencies
 - variables.scss
 - Logo design

## User story
 As a visitor on the site, I want find out more practical information about the cinema; for instance tickets and opening hours.

## Definition of done
 A nice looking menu (with styling!), both on desktop and mobile. Hover effects.

## Tests
 Mouseover a link to see hover effects.

**Comment by ved0** [comment]
Pull request:
https://github.com/saeraa/mellankalix/pull/55/

**Comment by JonathanHolmgren** [comment]
Headern ser bra ut i skrivbordsläge samt i mobilversion. Mobilversionen har hamburgaremeny och fungerar enligt önskat.
