### ISSUE TITLE
[0] Create logo

### ISSUE THREAD

**Issue by Arash-SJPI22** [saeraa/mellankalix#11]

**Comment by saeraa** [comment]
![Image](https://user-images.githubusercontent.com/99484730/209202474-b03dcb1f-c18e-44a7-b69f-83220c0b5507.png)

**Comment by saeraa** [comment]
SVG, transparent background:

![Image](https://user-images.githubusercontent.com/99484730/209317799-348e2c92-2fe4-4c49-b35b-681d354aba5a.svg)
