### ISSUE TITLE
[4] index.html: Karusell

### ISSUE THREAD

**Issue by saeraa** [saeraa/mellankalix#21]
## Details
Carousel underneath menu on index.html
Styling: carousel.scss
3 random movies from the database. With big images, title, button for tickets.
Animation for text + ticket button (slide in from below).
Automatic change slide every 3-5 seconds.
Buttons for next and previous slide.
If you want to, make the carousel look good on mobile. Else, hide it when going under a certain viewport width.

## Dependencies
 - Database with movies + images
 - Individual movie page to link to the ticket button

## Definition of done
 Spinning carousel with image and title. Can click prev and next. Can click ticket button. 

## Tests
 Can click prev button and get previous slide. Can click next button and get next slide. Can click ticket button and be redirected to a ticket page.

**Comment by ved0** [comment]
It looks good and it works good.
It fulfills all the requirements from the test section of the card! :100:
