### ISSUE TITLE
[3] index.html: Visningstider

### ISSUE THREAD

**Issue by Arash-SJPI22** [saeraa/mellankalix#22]
A side panel to the right of the movie lists on the startpage with a list of show times for today's and tomorrows showings of movies, opera, theater, art and concerts.
Each time and title is a clickable link and will take the user to the movie, opera, theater .... but just a place holder for the link now.
The list should be ordered by time, earliest time on top for each day.
A button at the bottom, if clicked will take the user to a new page listing all the movies, opera, theater and so on, with one month of today's date. Each day will list all the time slots for each showing. But just a placeholder for the link now.

Styling SCSS - currentShowtimes.scss
Some hover effect for the button and the links
Design up to the developer, artistic freedom!

Two designs: mobile menu: find a good solution maybe show it horizontaly above the movie lists insted?  desktop: it should be placed on the right and maybe be sticky?

Dependencies:

    variables.scss
    database.json

Definition of done: It creates an accurate list of today and tomorrows shows and clickable links. Have styling and hover effects. Mobile and desktop version.

Tests: Mouseover a link to see hover effects. If the time and title is a clickable link. If it shows all the listings of shows for today and tomorrow with time and title.

**Comment by Arash-SJPI22** [comment]
https://github.com/saeraa/mellankalix/pull/57

**Comment by saeraa** [comment]
Is it supposed to look like this? 👀

![Image](https://user-images.githubusercontent.com/99484730/210091199-2f2c9923-70c9-4f5d-84e5-19c7a1746bb2.png)

PS. The dates are in English when everything else on the page is in Swedish.

**Comment by JonathanHolmgren** [comment]
@Arash-SJPI22 Har testat och det ser bra ut, Men om jag förstår kunden rätt så har du ingen funktion som checkar om filmen visningstid är lika med dagens datum och då "skapar" element under "showtimes-today-header" respektive showtimes-tomorrow?

**Comment by Arash-SJPI22** [comment]
I will fix the date to be in swedish in mob-coding today and the height of it in mobiel view.
@JonathanHolmgren that is what the filterMovies function dose that Sara wrote and someone has re-enterd today and tomorrw headers that I removed. Will fix in todays mob-coding

**Comment by Arash-SJPI22** [comment]
Fixed
