### ISSUE TITLE
[2] index.html: Footer

### ISSUE THREAD

**Issue by JonathanHolmgren** [saeraa/mellankalix#23]
The footer section at the very bottom of a web page.

Sitemap
Contact information (Phone number, Email and address)
Social Media icons (placeholder path links)

Styling SCSS - footer.scss
Some hover effect
Design up to the developer, artistic freedom!

Two designs: mobile menu, desktop

Dependencies:
•	variables.scss
•	The different titles on the sitemap to should be linked to their page.

Definition of done:  When the footer consists of a sitemap, contact information, and social media icons and has a nice styling

Tests: When you click on the title for the page under the sitemap, you should be redirected to that site.

**Comment by ved0** [comment]
Pull request:
https://github.com/saeraa/mellankalix/pull/58

**Comment by JonathanHolmgren** [comment]
Kan se att footern är på plats och visar nödvändig information.
