### ISSUE TITLE
[4] index.html: Sökfunktion

### ISSUE THREAD

**Issue by saeraa** [saeraa/mellankalix#24]
## User story
 As a visitor on the site, I want to be able to search for a specific movie.

## Details
A looking glass button. When clicked, should take you to a search.html page. 
On the search page, there should be an input field and a search button. 
When you fill out the search field and press enter or click the search button, you should be shown a list of matching results. 
Styling: search.scss

Optional: 
When you click the looking glass, you get an input field sliding out on the same page you're on. When you enter some text, you get a bare bones list on the same page with options, and if you click on one of the options you get taken directly to the movie page.
[Example here](https://www.justwatch.com/us/movie/avatar-2009)

## Dependencies:
 - Movie cards
 - variables.scss

## Tests
 When you press the search button from the index.html, you should be redirected to search.html. 
When you enter `avatar` or `AVATAR` or `avATar` or `avatA` or `Avat` and press search, you should receive at least one result (Avatar: The way of water) in the list. 
When the input field is empty, the search button should be disabled.
You should be able to search either by pressing the button or pressing enter on your keyboard.
When you input `blah3879462764` in the search field, you should receive a message saying `Inga matchande föreställningar hittades för sökningen: blah3879462764.`

## Definition of done
  When all tests are OK. Design should look good. Use fonts and colors from variables.scss.

**Comment by ved0** [comment]
Tested it and it looks really nice!
It passes all the test requirements from the card.  :)
