### ISSUE TITLE
[3] index.html: Film-lista: Från API/Json fil

### ISSUE THREAD

**Issue by Arash-SJPI22** [saeraa/mellankalix#25]
A list of movie cards generated from an API or database.json file from the shows from today's date and a month forward but no more then 21 movies cards.
Each card should display the poster of the show and under the poster the title.
Each card is a link, if clicked will take the user to a new site with more information about the movie. Placeholder link will do for now.

Styling movieList.scss
Shadow on each card , with artistic freedom to design more.
Hover effect on each card

Two designs: 
mobile_ the "Visningstider" should also have a space to be shown, so no more then 1 or 2 cards per row.
desktop: No more then 3 cards on each row.

Dependencies:
variables.scss
database.json / API

Definition of done: It creates a random generate movies from current day and one month forward. Have styling and hover effects. Mobile and desktop version. Looks good.

Tests: Mouseover a card to see hover effects. The card is a clickable link. If it shows all the listings of shows for today and tomorrow with time and title.

**Comment by saeraa** [comment]
[Pull request](https://github.com/saeraa/mellankalix/pull/52)

**Comment by Arash-SJPI22** [comment]
Tested, works, links need to be updated when movie.html is done. Looks great!
