### ISSUE TITLE
[3] index.html: Menyn

### ISSUE THREAD

**Issue by saeraa** [saeraa/mellankalix#26]
## Details
Navigation menu for all the pages.
Links to all the pages: Under header `Repertoar`: `Hela bioprogrammet`, under header `Serverade salonger`: `Salong Bar Deco` etc. 
Design choice up to you, as long as you use the colors and fonts in the variables file.
If following the design on biografspegeln.se: Header with arrow, that opens (when clicked or mouseover) to show the detailed menu. Smooth animation. Hover effect when mousing over the examples.
Styling: navigation.scss

Extras:
If you're on page `Hela bioprogrammet`, then that link can be marked in some way. Color? Border? Underline?

## Dependencies
 - variables.scss

## Definition of done
A nice looking menu.
All the links should be placeholders for the time being. 
Hover effect.
Smooth animations.

## Tests
When clicking or hovering over a header in the menu, you should see a list of pages to visit. There should be a visible effect when hovering over a list item.

**Comment by Arash-SJPI22** [comment]
Tested on all pages and workes great!
