### ISSUE TITLE
[4] Create page: Film sida med mer detalj

### ISSUE THREAD

**Issue by saeraa** [saeraa/mellankalix#27]
## User story
As a visitor to the cinema, I want to be able to see more information about the movie I want to watch.

## Details
movie.html(?) page with dynamically rendered content depending on which movie you're on. 
Information that should be there: Title, genre. Description. Director, actors, country, age limit. Showtimes. Ticket button.
Embedded trailer. Poster, possibly other pictures.
Should look good. Follow colors and fonts as provided in variables.scss.
Styling in movieDetails.scss

_Suggestion: `page.com/#5` should render the movie with the index of 5 from database.json._

## Dependencies
- Movie database
- variables.scss

## Definition of done
All information about the movie should be on the page. It should be styled nicely according to the site style guide/card. It should look good on both mobile and desktop.

## Tests
I should be able to click the ticket button and be redirected to a page where it says "You want to book movie X"
I should be able to click play on the trailer and watch it.

**Comment by saeraa** [comment]
[Pull request](https://github.com/saeraa/mellankalix/pull/63)



![Image](https://user-images.githubusercontent.com/99484730/210072432-4b12c68a-2519-4432-aaff-e323899f87c8.png)

**Comment by JonathanHolmgren** [comment]
@saeraa Ser riktigt bra ut och har testat lite olika sidor och knappar. En liten fundering, hur ser det ut med först filmen i databasen? Var skapas ingen informationssida för denna?

**Comment by JonathanHolmgren** [comment]
Tror detta löser problemet, var ett "+" tecken innan "parameter.slice(1).match(/^\d+$/)?.input;".


![Image](https://user-images.githubusercontent.com/113441553/210274454-43f526ae-447f-438b-9f8f-90e793d22ba6.png)

**Comment by saeraa** [comment]
Nä, plustecknet är en liten fix för att få det till nummer istället för sträng. Problemet är att movieIndex blir 0, vilket är falsy i JavaScript. Så if-satsen nedanför behöver ändras till `if (!isNaN(movieIndex) && movieIndex ....`

Nice catch iaf, hade jag missat! 😉

**Comment by ved0** [comment]
Works like a charm and looks amazing. Great work! :1:
