### ISSUE TITLE
[1] Create page: REPERTOAR Kommande premiärer

### ISSUE THREAD

**Issue by saeraa** [saeraa/mellankalix#35]
**Details**

Create new page inspired by https://biografspegeln.se/#/content/24

Add heading

Add coming releases for the next 6 months (use static placeholder text)

Style the page

Make responsive

**Dependencies**

variables.scss

**Definition of done**

- Heading is added
- Comming releases are added 
- Styling is finished
- Looks good on mobile and desktop
- Header and footer is added

**Tests**

david

**Comment by ved0** [comment]
Tested and it looks good both on desktop and mobile.
The page shows the premieres of the upcoming movies

**Comment by Arash-SJPI22** [comment]
Why is it a static page ? We have the data to get the information from...
