### ISSUE TITLE
[2] Design: MovieCard

### ISSUE THREAD

**Issue by saeraa** [saeraa/mellankalix#46]
## Details

Design the scss/html for the movie cards to be shown on the different subpages on the site, for instance Klassiker / Frukostbio.

The card should contain a showtime, the poster, title. A button linking to the individual movie page, and another button for tickets.

## Definition of done
The card should show the correct information in a nice manner.

## Dependencies
 - variables.scss
 - database.json

**Comment by saeraa** [comment]
PR here: https://github.com/saeraa/mellankalix/pull/50



![Image](https://user-images.githubusercontent.com/99484730/209400003-0ce5d076-beec-4013-9ade-54a61fb3a905.png)

**Comment by saeraa** [comment]
Testas på: https://saeraa.github.io/mellankalix/placeholder.html

**Comment by JonathanHolmgren** [comment]
Testar kortet och det ser bra ut.
