### ISSUE TITLE
[1] Create page: Om Oss

### ISSUE THREAD

**Issue by saeraa** [saeraa/mellankalix#5]
**Details**
________________________________________

New page for about us, e.g. aboutUs.html.
On this page, the user should receive all the necessary information regarding the movie theater e.g. 
History.
Information about the saloons .
Information about the owner.
 
For inspiration: https://biografspegeln.se/#/content/3

Styling SCSS - ticketInfo.scss
Design is up to the developer, artistic freedom. But the design must follow the website's color codes.
Two designs: mobile menu, desktop

**Dependencies**
________________________________________
•	variables.scss

**User Story**
________________________________________
As a user, I want to be able to find information about the movie theater that they will visit.

**Definition of done**
________________________________________
When the page consists of all of the necessary information regarding the movie theater and the styling follow the website’s color codes.

**Tests**
________________________________________

Once you have navigated to the aboutUs page, you should be able to see information about the movie theater.

**Comment by Arash-SJPI22** [comment]
https://github.com/saeraa/mellankalix/pull/61

**Comment by ved0** [comment]
Funkar bra och ser bra ut! :) Testad och klar!
