### ISSUE TITLE
[1] Create page: Öppettider & Kontakt

### ISSUE THREAD

**Issue by saeraa** [saeraa/mellankalix#6]
User story: As a visitor of the cinema, I want to be able to get in touch with the cinema and also see the opening hours.

Details: A site that is displaying the contact information and the opening hours of the cinema.
Colors and fonts should be used from the variables file. The design of the site is up to the implementer.

Two designs: mobile menu, desktop

Dependencies: variables.scss

Definition of done: A nice looking page that is following the overall design of the website. Displaying both contact information and opening hours.

Test: When navigating to this page, it should be displaying contact and open hours in a nice way. If it does, it works.

**Comment by Arash-SJPI22** [comment]
https://github.com/saeraa/mellankalix/pull/60

**Comment by ved0** [comment]
Tested and its doing exactly what it should and it works fine :)
