### ISSUE TITLE
[1] Create page: Biljettinfo

### ISSUE THREAD

**Issue by saeraa** [saeraa/mellankalix#7]
**Details**
________________________________________

New page for ticket information, e.g. ticketInfo.html.
On this page, the user should receive all the necessary information regarding the tickets e.g. 
Question and answers.
The different types of tickets.
No refunds/change
Ticket release
For inspiration: https://biografspegeln.se/#/content/2

Styling SCSS - ticketInfo.scss
Design is up to the developer, artistic freedom. But the design must follow the website's color codes.
Two designs: mobile menu, desktop

**Dependencies**
________________________________________

•	variables.scss

**User Story**
________________________________________

As a user, I want to be able to find information about the tickets that I will buy.

**Definition of done**
________________________________________
When the page consists of all of the necessary information regarding the tickets and the styling follow the website’s color codes.

**Tests**
________________________________________

Once you have navigated to the ticketInfo page, you should be able to see information about the ticket.

**Comment by ved0** [comment]
pull request: https://github.com/saeraa/mellankalix/pull/71

**Comment by JonathanHolmgren** [comment]
A test is done, and it seems to work fine.
