### ISSUE TITLE
[1] Create page: Köp presentkort

### ISSUE THREAD

**Issue by Arash-SJPI22** [saeraa/mellankalix#8]
## Details
giftcertificate.html (???) 

## Dependencies
 - menu, header, footer etc

## Tests

**Comment by saeraa** [comment]
Images aren't loading :(

Also, the font for "Presentkort" is different than the others in the project.

And remove/purchase buttons should probably be in Swedish to match the rest of the site.


![Image](https://user-images.githubusercontent.com/99484730/210272842-c269da8f-84a4-4356-a024-f85624306525.png)

**Comment by Arash-SJPI22** [comment]
Works fine for me, all images load. 
But on line 63 in giftcertificate.js you should remove "console.log(title, price, imageSrc);" :D

**Comment by Arash-SJPI22** [comment]
Tested and working!
